version: "3"
services:
  app: 
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_app
    image: api_app
    volumes:
      - .:/home/node/app
    ports:
      - "8002:8002"
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    ports:
      - "27017:27017"